---
- name: "Provision Ansible LAB in Azure"
  hosts: localhost
  gather_facts: no

  tasks:
    - import_tasks: "tasks/create_resource_group.yaml"

    - import_tasks: "tasks/create_network.yaml"
  
    - name: "Create VM CentOS 1"
      with:
      import_role:
        name: azure_vm
      vars:
        vm_name: "centos1"
        default_username: "mouimet"
        vm_size: Standard_D2_v3
        ip_address: "10.0.0.11"
        security_rules: "{{ default_security_rules }}"
        image:
          offer: Centos
          publisher: OpenLogic
          sku: '7.4'
          version: latest

    - name: "Create VM CentOS 2"
      import_role:
        name: azure_vm
      vars:
        vm_name: "centos2"
        default_username: "mouimet"
        vm_size: Standard_D2_v3
        ip_address: "10.0.0.12"
        security_rules: "{{ default_security_rules }}"
        image:
          offer: Centos
          publisher: OpenLogic
          sku: '7.4'
          version: latest

